# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [3.22.3] # Specify your Flutter version here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

  #  - name: Set up Flutter
  #    uses: subosito/flutter-action@v2.14.0
   #   with:
   #     flutter-version: ${{ matrix.flutter-version }}

  #  - name: Install dependencies
  #    run: flutter pub upgrade --major-versions

 #   - name: Clean Flutter build
   #   run: flutter clean

    # - name: Build APK
    #  run: flutter build apk --release 

    # - name: Build APK
    #   run: flutter build apk --debug --split-per-abi
